package com.ejemplo.vaadin.admusuarios;

import com.ejemplo.vaadin.entidades.Usuario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Form;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class UsuarioForm extends Form {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	//@AutoGenerated
	//private AbsoluteLayout mainLayout;
	
	@AutoGenerated
	private Button btInsertar;
	
	@AutoGenerated
	private Button btnReset;
	
	@AutoGenerated
	private TextField txtClave;
	
	@AutoGenerated
	private TextField txtCorreo;
	
	@AutoGenerated
	private TextField txtApellidos;
	
	@AutoGenerated
	private TextField txtNombre;
	
	@AutoGenerated
	private Label label_1;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UsuarioForm() {
	
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("200px");
		label_1.setHeight("-1px");
		label_1.setValue("Mantenimiento de Usuarios");
	//	mainLayout.addComponent(label_1, "top:20.0px;left:20.0px;");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("177px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		txtNombre.setRequiredError("Debes escribir un nombre");
		//mainLayout.addComponent(txtNombre, "top:80.0px;left:23.0px;");
		
		// txtApellidos
		txtApellidos = new TextField();
		txtApellidos.setCaption("Apellidos");
		txtApellidos.setImmediate(false);
		txtApellidos.setWidth("416px");
		txtApellidos.setHeight("-1px");
		txtApellidos.setRequired(true);
		txtApellidos.setRequiredError("Debes escribir un apellido");
		//mainLayout.addComponent(txtApellidos, "top:80.0px;left:284.0px;");
		
		// txtCorreo
		txtCorreo = new TextField();
		txtCorreo.setCaption("Correo");
		txtCorreo.setImmediate(false);
		txtCorreo.setWidth("377px");
		txtCorreo.setHeight("-1px");
		txtCorreo.setRequired(true);
		txtCorreo.addValidator(new EmailValidator("El eamil es obligatorio"));
		//mainLayout.addComponent(txtCorreo, "top:156.0px;left:23.0px;");
		
		// txtClave
		txtClave = new TextField();
		txtClave.setCaption("Clave");
		txtClave.setImmediate(false);
		txtClave.setWidth("-1px");
		txtClave.setHeight("-1px");
		txtClave.setRequired(true);
		txtClave.setRequiredError("Debes escribir la clave");
		//mainLayout.addComponent(txtClave, "top:156.0px;left:423.0px;");
		
		
		// btnReset
		btnReset = new Button();
		btnReset.setCaption("Limpiar");
		btnReset.setImmediate(false);
		btnReset.setWidth("-1px");
		btnReset.setHeight("-1px");
		//mainLayout.addComponent(btnReset, "top:294.0px;left:60.0px;");
		
		// btInsertar
		btInsertar = new Button();
		btInsertar.setCaption("Insertar Usuario");
		btInsertar.setImmediate(false);
		btInsertar.setWidth("233px");
		btInsertar.setHeight("-1px");
		//mainLayout.addComponent(btInsertar, "top:294.0px;left:190.0px;");
		addField("txtNombre",txtNombre);
		addField("txtApellidos",txtApellidos);
		addField("txtCorreo",txtCorreo);
		addField("txtClave",txtClave);
		addField("btnReset",btnReset);
		addField("btnInsertar",btInsertar);
		//return mainLayout;
	}
	
	public void entidadAFormulario(Usuario usuario){
		txtNombre.setValue(usuario.getNombres());
		txtApellidos.setValue(usuario.getApellidos());
		txtCorreo.setValue(usuario.getCorreo());
		txtClave.setValue(usuario.getClave());
		
		
	}
	
public Usuario formularioAEntidad(){
	Usuario user= new Usuario();
	user.setNombres(txtNombre.getValue().toString());
	user.setApellidos(txtApellidos.getValue().toString());
	user.setClave(txtClave.getValue().toString());
	user.setCorreo(txtCorreo.getValue().toString());
	return user;
	}

public Button getBtInsertar() {
	return btInsertar;
}

public void setBtInsertar(Button btInsertar) {
	this.btInsertar = btInsertar;
}

public Button getBtnReset() {
	return btnReset;
}

public void setBtnReset(Button btnReset) {
	this.btnReset = btnReset;
}

public TextField getTxtClave() {
	return txtClave;
}

public void setTxtClave(TextField txtClave) {
	this.txtClave = txtClave;
}

public TextField getTxtCorreo() {
	return txtCorreo;
}

public void setTxtCorreo(TextField txtCorreo) {
	this.txtCorreo = txtCorreo;
}

public TextField getTxtApellidos() {
	return txtApellidos;
}

public void setTxtApellidos(TextField txtApellidos) {
	this.txtApellidos = txtApellidos;
}

public TextField getTxtNombre() {
	return txtNombre;
}

public void setTxtNombre(TextField txtNombre) {
	this.txtNombre = txtNombre;
}

public Label getLabel_1() {
	return label_1;
}

public void setLabel_1(Label label_1) {
	this.label_1 = label_1;
}



}
